/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserRouteImport } from './routes/user'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KtAdminRouteImport } from './routes/kt-admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserWithdrawRouteImport } from './routes/user/withdraw'
import { Route as UserTasksRouteImport } from './routes/user/tasks'
import { Route as UserSpinRouteImport } from './routes/user/spin'
import { Route as UserReferRouteImport } from './routes/user/refer'
import { Route as UserProfileRouteImport } from './routes/user/profile'
import { Route as UserPackagesRouteImport } from './routes/user/packages'
import { Route as UserHistoryRouteImport } from './routes/user/history'
import { Route as UserDepositRouteImport } from './routes/user/deposit'
import { Route as UserDashboardRouteImport } from './routes/user/dashboard'
import { Route as KtAdminUsersRouteImport } from './routes/kt-admin.users'
import { Route as KtAdminTasksRouteImport } from './routes/kt-admin.tasks'
import { Route as KtAdminLoginRouteImport } from './routes/kt-admin.login'
import { Route as KtAdminEarningsRouteImport } from './routes/kt-admin.earnings'
import { Route as KtAdminDashboardRouteImport } from './routes/kt-admin.dashboard'
import { Route as ApiSplatRouteImport } from './routes/api/$'

const UserRoute = UserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KtAdminRoute = KtAdminRouteImport.update({
  id: '/kt-admin',
  path: '/kt-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserWithdrawRoute = UserWithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => UserRoute,
} as any)
const UserTasksRoute = UserTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => UserRoute,
} as any)
const UserSpinRoute = UserSpinRouteImport.update({
  id: '/spin',
  path: '/spin',
  getParentRoute: () => UserRoute,
} as any)
const UserReferRoute = UserReferRouteImport.update({
  id: '/refer',
  path: '/refer',
  getParentRoute: () => UserRoute,
} as any)
const UserProfileRoute = UserProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => UserRoute,
} as any)
const UserPackagesRoute = UserPackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => UserRoute,
} as any)
const UserHistoryRoute = UserHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => UserRoute,
} as any)
const UserDepositRoute = UserDepositRouteImport.update({
  id: '/deposit',
  path: '/deposit',
  getParentRoute: () => UserRoute,
} as any)
const UserDashboardRoute = UserDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => UserRoute,
} as any)
const KtAdminUsersRoute = KtAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => KtAdminRoute,
} as any)
const KtAdminTasksRoute = KtAdminTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => KtAdminRoute,
} as any)
const KtAdminLoginRoute = KtAdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => KtAdminRoute,
} as any)
const KtAdminEarningsRoute = KtAdminEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => KtAdminRoute,
} as any)
const KtAdminDashboardRoute = KtAdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => KtAdminRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kt-admin': typeof KtAdminRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/user': typeof UserRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/kt-admin/dashboard': typeof KtAdminDashboardRoute
  '/kt-admin/earnings': typeof KtAdminEarningsRoute
  '/kt-admin/login': typeof KtAdminLoginRoute
  '/kt-admin/tasks': typeof KtAdminTasksRoute
  '/kt-admin/users': typeof KtAdminUsersRoute
  '/user/dashboard': typeof UserDashboardRoute
  '/user/deposit': typeof UserDepositRoute
  '/user/history': typeof UserHistoryRoute
  '/user/packages': typeof UserPackagesRoute
  '/user/profile': typeof UserProfileRoute
  '/user/refer': typeof UserReferRoute
  '/user/spin': typeof UserSpinRoute
  '/user/tasks': typeof UserTasksRoute
  '/user/withdraw': typeof UserWithdrawRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kt-admin': typeof KtAdminRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/user': typeof UserRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/kt-admin/dashboard': typeof KtAdminDashboardRoute
  '/kt-admin/earnings': typeof KtAdminEarningsRoute
  '/kt-admin/login': typeof KtAdminLoginRoute
  '/kt-admin/tasks': typeof KtAdminTasksRoute
  '/kt-admin/users': typeof KtAdminUsersRoute
  '/user/dashboard': typeof UserDashboardRoute
  '/user/deposit': typeof UserDepositRoute
  '/user/history': typeof UserHistoryRoute
  '/user/packages': typeof UserPackagesRoute
  '/user/profile': typeof UserProfileRoute
  '/user/refer': typeof UserReferRoute
  '/user/spin': typeof UserSpinRoute
  '/user/tasks': typeof UserTasksRoute
  '/user/withdraw': typeof UserWithdrawRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kt-admin': typeof KtAdminRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/user': typeof UserRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/kt-admin/dashboard': typeof KtAdminDashboardRoute
  '/kt-admin/earnings': typeof KtAdminEarningsRoute
  '/kt-admin/login': typeof KtAdminLoginRoute
  '/kt-admin/tasks': typeof KtAdminTasksRoute
  '/kt-admin/users': typeof KtAdminUsersRoute
  '/user/dashboard': typeof UserDashboardRoute
  '/user/deposit': typeof UserDepositRoute
  '/user/history': typeof UserHistoryRoute
  '/user/packages': typeof UserPackagesRoute
  '/user/profile': typeof UserProfileRoute
  '/user/refer': typeof UserReferRoute
  '/user/spin': typeof UserSpinRoute
  '/user/tasks': typeof UserTasksRoute
  '/user/withdraw': typeof UserWithdrawRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/kt-admin'
    | '/login'
    | '/register'
    | '/user'
    | '/api/$'
    | '/kt-admin/dashboard'
    | '/kt-admin/earnings'
    | '/kt-admin/login'
    | '/kt-admin/tasks'
    | '/kt-admin/users'
    | '/user/dashboard'
    | '/user/deposit'
    | '/user/history'
    | '/user/packages'
    | '/user/profile'
    | '/user/refer'
    | '/user/spin'
    | '/user/tasks'
    | '/user/withdraw'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/kt-admin'
    | '/login'
    | '/register'
    | '/user'
    | '/api/$'
    | '/kt-admin/dashboard'
    | '/kt-admin/earnings'
    | '/kt-admin/login'
    | '/kt-admin/tasks'
    | '/kt-admin/users'
    | '/user/dashboard'
    | '/user/deposit'
    | '/user/history'
    | '/user/packages'
    | '/user/profile'
    | '/user/refer'
    | '/user/spin'
    | '/user/tasks'
    | '/user/withdraw'
  id:
    | '__root__'
    | '/'
    | '/kt-admin'
    | '/login'
    | '/register'
    | '/user'
    | '/api/$'
    | '/kt-admin/dashboard'
    | '/kt-admin/earnings'
    | '/kt-admin/login'
    | '/kt-admin/tasks'
    | '/kt-admin/users'
    | '/user/dashboard'
    | '/user/deposit'
    | '/user/history'
    | '/user/packages'
    | '/user/profile'
    | '/user/refer'
    | '/user/spin'
    | '/user/tasks'
    | '/user/withdraw'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KtAdminRoute: typeof KtAdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  UserRoute: typeof UserRouteWithChildren
  ApiSplatRoute: typeof ApiSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kt-admin': {
      id: '/kt-admin'
      path: '/kt-admin'
      fullPath: '/kt-admin'
      preLoaderRoute: typeof KtAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/withdraw': {
      id: '/user/withdraw'
      path: '/withdraw'
      fullPath: '/user/withdraw'
      preLoaderRoute: typeof UserWithdrawRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/tasks': {
      id: '/user/tasks'
      path: '/tasks'
      fullPath: '/user/tasks'
      preLoaderRoute: typeof UserTasksRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/spin': {
      id: '/user/spin'
      path: '/spin'
      fullPath: '/user/spin'
      preLoaderRoute: typeof UserSpinRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/refer': {
      id: '/user/refer'
      path: '/refer'
      fullPath: '/user/refer'
      preLoaderRoute: typeof UserReferRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/profile': {
      id: '/user/profile'
      path: '/profile'
      fullPath: '/user/profile'
      preLoaderRoute: typeof UserProfileRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/packages': {
      id: '/user/packages'
      path: '/packages'
      fullPath: '/user/packages'
      preLoaderRoute: typeof UserPackagesRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/history': {
      id: '/user/history'
      path: '/history'
      fullPath: '/user/history'
      preLoaderRoute: typeof UserHistoryRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/deposit': {
      id: '/user/deposit'
      path: '/deposit'
      fullPath: '/user/deposit'
      preLoaderRoute: typeof UserDepositRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/dashboard': {
      id: '/user/dashboard'
      path: '/dashboard'
      fullPath: '/user/dashboard'
      preLoaderRoute: typeof UserDashboardRouteImport
      parentRoute: typeof UserRoute
    }
    '/kt-admin/users': {
      id: '/kt-admin/users'
      path: '/users'
      fullPath: '/kt-admin/users'
      preLoaderRoute: typeof KtAdminUsersRouteImport
      parentRoute: typeof KtAdminRoute
    }
    '/kt-admin/tasks': {
      id: '/kt-admin/tasks'
      path: '/tasks'
      fullPath: '/kt-admin/tasks'
      preLoaderRoute: typeof KtAdminTasksRouteImport
      parentRoute: typeof KtAdminRoute
    }
    '/kt-admin/login': {
      id: '/kt-admin/login'
      path: '/login'
      fullPath: '/kt-admin/login'
      preLoaderRoute: typeof KtAdminLoginRouteImport
      parentRoute: typeof KtAdminRoute
    }
    '/kt-admin/earnings': {
      id: '/kt-admin/earnings'
      path: '/earnings'
      fullPath: '/kt-admin/earnings'
      preLoaderRoute: typeof KtAdminEarningsRouteImport
      parentRoute: typeof KtAdminRoute
    }
    '/kt-admin/dashboard': {
      id: '/kt-admin/dashboard'
      path: '/dashboard'
      fullPath: '/kt-admin/dashboard'
      preLoaderRoute: typeof KtAdminDashboardRouteImport
      parentRoute: typeof KtAdminRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface KtAdminRouteChildren {
  KtAdminDashboardRoute: typeof KtAdminDashboardRoute
  KtAdminEarningsRoute: typeof KtAdminEarningsRoute
  KtAdminLoginRoute: typeof KtAdminLoginRoute
  KtAdminTasksRoute: typeof KtAdminTasksRoute
  KtAdminUsersRoute: typeof KtAdminUsersRoute
}

const KtAdminRouteChildren: KtAdminRouteChildren = {
  KtAdminDashboardRoute: KtAdminDashboardRoute,
  KtAdminEarningsRoute: KtAdminEarningsRoute,
  KtAdminLoginRoute: KtAdminLoginRoute,
  KtAdminTasksRoute: KtAdminTasksRoute,
  KtAdminUsersRoute: KtAdminUsersRoute,
}

const KtAdminRouteWithChildren =
  KtAdminRoute._addFileChildren(KtAdminRouteChildren)

interface UserRouteChildren {
  UserDashboardRoute: typeof UserDashboardRoute
  UserDepositRoute: typeof UserDepositRoute
  UserHistoryRoute: typeof UserHistoryRoute
  UserPackagesRoute: typeof UserPackagesRoute
  UserProfileRoute: typeof UserProfileRoute
  UserReferRoute: typeof UserReferRoute
  UserSpinRoute: typeof UserSpinRoute
  UserTasksRoute: typeof UserTasksRoute
  UserWithdrawRoute: typeof UserWithdrawRoute
}

const UserRouteChildren: UserRouteChildren = {
  UserDashboardRoute: UserDashboardRoute,
  UserDepositRoute: UserDepositRoute,
  UserHistoryRoute: UserHistoryRoute,
  UserPackagesRoute: UserPackagesRoute,
  UserProfileRoute: UserProfileRoute,
  UserReferRoute: UserReferRoute,
  UserSpinRoute: UserSpinRoute,
  UserTasksRoute: UserTasksRoute,
  UserWithdrawRoute: UserWithdrawRoute,
}

const UserRouteWithChildren = UserRoute._addFileChildren(UserRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KtAdminRoute: KtAdminRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  UserRoute: UserRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
