/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KtAdminLoginRouteImport } from './routes/kt-admin-login'
import { Route as KtAdminRouteImport } from './routes/kt-admin'
import { Route as UserRouteImport } from './routes/_user'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KtAdminUsersRouteImport } from './routes/kt-admin.users'
import { Route as KtAdminTasksRouteImport } from './routes/kt-admin.tasks'
import { Route as KtAdminEarningsRouteImport } from './routes/kt-admin.earnings'
import { Route as KtAdminDashboardRouteImport } from './routes/kt-admin.dashboard'
import { Route as UserTasksRouteImport } from './routes/_user/tasks'
import { Route as UserHistoryRouteImport } from './routes/_user/history'
import { Route as UserDashboardRouteImport } from './routes/_user/dashboard'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KtAdminLoginRoute = KtAdminLoginRouteImport.update({
  id: '/kt-admin-login',
  path: '/kt-admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const KtAdminRoute = KtAdminRouteImport.update({
  id: '/kt-admin',
  path: '/kt-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const UserRoute = UserRouteImport.update({
  id: '/_user',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KtAdminUsersRoute = KtAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => KtAdminRoute,
} as any)
const KtAdminTasksRoute = KtAdminTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => KtAdminRoute,
} as any)
const KtAdminEarningsRoute = KtAdminEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => KtAdminRoute,
} as any)
const KtAdminDashboardRoute = KtAdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => KtAdminRoute,
} as any)
const UserTasksRoute = UserTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => UserRoute,
} as any)
const UserHistoryRoute = UserHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => UserRoute,
} as any)
const UserDashboardRoute = UserDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => UserRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kt-admin': typeof KtAdminRouteWithChildren
  '/kt-admin-login': typeof KtAdminLoginRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof UserDashboardRoute
  '/history': typeof UserHistoryRoute
  '/tasks': typeof UserTasksRoute
  '/kt-admin/dashboard': typeof KtAdminDashboardRoute
  '/kt-admin/earnings': typeof KtAdminEarningsRoute
  '/kt-admin/tasks': typeof KtAdminTasksRoute
  '/kt-admin/users': typeof KtAdminUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kt-admin': typeof KtAdminRouteWithChildren
  '/kt-admin-login': typeof KtAdminLoginRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof UserDashboardRoute
  '/history': typeof UserHistoryRoute
  '/tasks': typeof UserTasksRoute
  '/kt-admin/dashboard': typeof KtAdminDashboardRoute
  '/kt-admin/earnings': typeof KtAdminEarningsRoute
  '/kt-admin/tasks': typeof KtAdminTasksRoute
  '/kt-admin/users': typeof KtAdminUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_user': typeof UserRouteWithChildren
  '/kt-admin': typeof KtAdminRouteWithChildren
  '/kt-admin-login': typeof KtAdminLoginRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_user/dashboard': typeof UserDashboardRoute
  '/_user/history': typeof UserHistoryRoute
  '/_user/tasks': typeof UserTasksRoute
  '/kt-admin/dashboard': typeof KtAdminDashboardRoute
  '/kt-admin/earnings': typeof KtAdminEarningsRoute
  '/kt-admin/tasks': typeof KtAdminTasksRoute
  '/kt-admin/users': typeof KtAdminUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/kt-admin'
    | '/kt-admin-login'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/history'
    | '/tasks'
    | '/kt-admin/dashboard'
    | '/kt-admin/earnings'
    | '/kt-admin/tasks'
    | '/kt-admin/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/kt-admin'
    | '/kt-admin-login'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/history'
    | '/tasks'
    | '/kt-admin/dashboard'
    | '/kt-admin/earnings'
    | '/kt-admin/tasks'
    | '/kt-admin/users'
  id:
    | '__root__'
    | '/'
    | '/_user'
    | '/kt-admin'
    | '/kt-admin-login'
    | '/login'
    | '/register'
    | '/_user/dashboard'
    | '/_user/history'
    | '/_user/tasks'
    | '/kt-admin/dashboard'
    | '/kt-admin/earnings'
    | '/kt-admin/tasks'
    | '/kt-admin/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UserRoute: typeof UserRouteWithChildren
  KtAdminRoute: typeof KtAdminRouteWithChildren
  KtAdminLoginRoute: typeof KtAdminLoginRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kt-admin-login': {
      id: '/kt-admin-login'
      path: '/kt-admin-login'
      fullPath: '/kt-admin-login'
      preLoaderRoute: typeof KtAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kt-admin': {
      id: '/kt-admin'
      path: '/kt-admin'
      fullPath: '/kt-admin'
      preLoaderRoute: typeof KtAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_user': {
      id: '/_user'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof UserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kt-admin/users': {
      id: '/kt-admin/users'
      path: '/users'
      fullPath: '/kt-admin/users'
      preLoaderRoute: typeof KtAdminUsersRouteImport
      parentRoute: typeof KtAdminRoute
    }
    '/kt-admin/tasks': {
      id: '/kt-admin/tasks'
      path: '/tasks'
      fullPath: '/kt-admin/tasks'
      preLoaderRoute: typeof KtAdminTasksRouteImport
      parentRoute: typeof KtAdminRoute
    }
    '/kt-admin/earnings': {
      id: '/kt-admin/earnings'
      path: '/earnings'
      fullPath: '/kt-admin/earnings'
      preLoaderRoute: typeof KtAdminEarningsRouteImport
      parentRoute: typeof KtAdminRoute
    }
    '/kt-admin/dashboard': {
      id: '/kt-admin/dashboard'
      path: '/dashboard'
      fullPath: '/kt-admin/dashboard'
      preLoaderRoute: typeof KtAdminDashboardRouteImport
      parentRoute: typeof KtAdminRoute
    }
    '/_user/tasks': {
      id: '/_user/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof UserTasksRouteImport
      parentRoute: typeof UserRoute
    }
    '/_user/history': {
      id: '/_user/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof UserHistoryRouteImport
      parentRoute: typeof UserRoute
    }
    '/_user/dashboard': {
      id: '/_user/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof UserDashboardRouteImport
      parentRoute: typeof UserRoute
    }
  }
}

interface UserRouteChildren {
  UserDashboardRoute: typeof UserDashboardRoute
  UserHistoryRoute: typeof UserHistoryRoute
  UserTasksRoute: typeof UserTasksRoute
}

const UserRouteChildren: UserRouteChildren = {
  UserDashboardRoute: UserDashboardRoute,
  UserHistoryRoute: UserHistoryRoute,
  UserTasksRoute: UserTasksRoute,
}

const UserRouteWithChildren = UserRoute._addFileChildren(UserRouteChildren)

interface KtAdminRouteChildren {
  KtAdminDashboardRoute: typeof KtAdminDashboardRoute
  KtAdminEarningsRoute: typeof KtAdminEarningsRoute
  KtAdminTasksRoute: typeof KtAdminTasksRoute
  KtAdminUsersRoute: typeof KtAdminUsersRoute
}

const KtAdminRouteChildren: KtAdminRouteChildren = {
  KtAdminDashboardRoute: KtAdminDashboardRoute,
  KtAdminEarningsRoute: KtAdminEarningsRoute,
  KtAdminTasksRoute: KtAdminTasksRoute,
  KtAdminUsersRoute: KtAdminUsersRoute,
}

const KtAdminRouteWithChildren =
  KtAdminRoute._addFileChildren(KtAdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UserRoute: UserRouteWithChildren,
  KtAdminRoute: KtAdminRouteWithChildren,
  KtAdminLoginRoute: KtAdminLoginRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
